# -*- coding: utf-8 -*-
"""AI FIRST LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NacOeDkdVmilsutiIkJ8T_-ooK9a9fv

# Hello

Hello

```
# This is formatted as code
```
print("hello world")
"""

print("hello world")

a=6
b=5
c=a+b
print(c)

"""# Addition"""

a=25
b=35
c=a+b
print(c)

"""# Subtraction"""

a=50
b=60
c=a-b
print(c)

"""# Multiplication"""

a=8
b=5
result=a*b
print("Product", result)

"""# Division"""

a=80
b=10
result=a/b
print("Answer", result)