# -*- coding: utf-8 -*-
"""KNN_ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyqH4U0K0mK8Pbd-rxq5QVAWfVUIl2QG
"""

# Import required libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Step 1: Load dataset
data = load_iris()         # Load the Iris dataset
X = data.data              # Features (inputs)
y = data.target            # Labels (outputs)

# Step 2: Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=40
)

# Step 3: Initialize and train the KNN classifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train, y_train)

# Step 4: Make predictions
y_pred = knn.predict(X_test)

# Step 5: Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy:.2f}")

# Step 6: Evaluate accuracy for both
y_train_pred = knn.predict(X_train) # Predict on training data
y_test_pred = knn.predict(X_test)   # Predict on testing data

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Step 7: Print the results
print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)