# -*- coding: utf-8 -*-
"""Lab 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5M99J8jqBr020HUjyW_4VQKT-opPkVc

# **Task 1: Lists**
"""

numbers = [12, 45, 7, 23, 89, 34, 56, 78, 10, 5] # list of 10 integers


print("List of numbers:", numbers)
print("Sum:", sum(numbers)) # sum of list
print("Maximum:", max(numbers)) # max num
print("Minimum:", min(numbers))# min num

# Add element at the end
numbers.append(99)
print("After adding 99:", numbers)

# Add element at specific position (index 2)
numbers.insert(2, 50)
print("After inserting 50 at index 2:", numbers)

# Remove element by value
numbers.remove(23)
print("After removing 23:", numbers)

# Remove element by index
numbers.pop(4)   # removes element at index 4
print("After removing element at index 4:", numbers)

# Sort in ascending order
numbers.sort()
print("After sorting in ascending order:", numbers)

# Sort in descending order
numbers.sort(reverse=True)
print("After sorting in descending order:", numbers)

"""# **Task 2: Tuples**"""

cars = ("Bughatti", "lamborghini", "mercedes", "ferrari", "Porsche")
print("Original tuple:", cars)

# Convert the tuple to a list
cars_list = list(cars)
print("Converted to list:", cars_list)

# The following line will still cause an error as it's commented out and shows tuple immutability.
# To demonstrate list mutability, you could uncomment and modify cars_list.
# cars[0] = "Honda"

"""# **Task 3: Sets**"""

# Create two sets
set1 = {10, 20, 30, 40, 50, 60}
set2 = {50, 60, 70, 80, 90, 100}

print("Set 1:", set1)
print("Set 2:", set2)

# Union of the two sets
union_set = set1.union(set2)
print("Union of Set 1 and Set 2:", union_set)

# Intersection of the two sets
intersection_set = set1.intersection(set2)
print("Intersection of Set 1 and Set 2:", intersection_set)

# Difference of the two sets (elements in set1 but not in set2)
difference_set1 = set1.difference(set2)
print("Difference (Set 1 - Set 2):", difference_set1)

# Difference of the two sets (elements in set2 but not in set1)
difference_set2 = set2.difference(set1)
print("Difference (Set 2 - Set 1):", difference_set2)

"""# **Task 4: Dictionary**"""



# Create a dictionary of 5 Muslim names
muslim_names = {
    "Male1": "Muhammad",
    "Female1": "Aisha",
    "Male2": "Ali",
    "Female2": "Fatima",
    "Male3": "Omar"
}

print("Dictionary:", muslim_names)

# Print keys
print("\nKeys:", muslim_names.keys())

# Print values
print("Values:", muslim_names.values())