# -*- coding: utf-8 -*-
"""UNSW-NB15_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMcDsFaqqvkLISc7G_O54bckAWsjFy1j

# Data Set
"""

import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;

file_path = '/content/drive/MyDrive/AI Lab/UNSW-NB15_1.csv'
print(file_path)

data = pd.read_csv(file_path)
print(data.head())

# Assuming 'udp' is the column name, replace it if it's different based on your data's actual column names
# You can verify the column names using data.columns

# Bar chart for 'udp' column
plt.figure(figsize=(10, 6))
data['udp'].value_counts().plot(kind='bar')
plt.title('Distribution of UDP values')
plt.xlabel('UDP values')
plt.ylabel('Count')
plt.show()

# Pie chart for 'udp' column
plt.figure(figsize=(8, 8))
data['udp'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribution of UDP values')
plt.ylabel('') # Remove default y-label for pie chart
plt.show()

data = pd.read_csv(file_path)
print(data.shape)

data = pd.read_csv(file_path)
print(data.columns)

data = pd.read_csv(file_path)
print(data.info())

data = pd.read_csv(file_path)
print(data.describe())

# Check the size of the DataFrame (number of instances and features)
print("Shape of the DataFrame:", data.shape)

# Check for null values
print("\nNull values per column:\n", data.isnull().sum())

# Check for duplicate rows
print("\nNumber of duplicate rows:", data.duplicated().sum())

# Get information about the features and their data types (instances and features are also included here)
print("\nDataFrame Information:\n")
data.info()